version: '2.4'

services:
    app:
        container_name: container_golang_jpk_generator
        build:
            context: docker/go
        ports:
            - "6060:6060"
        volumes:
            - ./:/go/pkg/app
        working_dir: /go/pkg/app
        command: go run main.go
    mysql:
        container_name: container_mysql
        image: mysql:5.7
        volumes:
          - "./../docker/volumes/jpk_generator/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "jpk_generator"
            MYSQL_USER: "root"
        ports:
          - "3306:3306"
